connector_image: airbyte/source-gitlab:dev
tests:
  spec:
    - spec_path: "source_gitlab/spec.json"
      backward_compatibility_tests_config:
        disable_for_version: "0.1.10"
  connection:
    - config_path: "secrets/config.json"
      status: "succeed"
    - config_path: "secrets/config_oauth.json"
      status: "succeed"
    - config_path: "integration_tests/invalid_config.json"
      status: "failed"
  discovery:
    - config_path: "secrets/config.json"
      backward_compatibility_tests_config:
        disable_for_version: "0.1.10"
    - config_path: "secrets/config_oauth.json"
      backward_compatibility_tests_config:
        disable_for_version: "0.1.10"
  basic_read:
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/configured_catalog.json"
      empty_streams: ["group_issue_boards"]
      expect_records:
        path: "integration_tests/expected_records.txt"
    - config_path: "secrets/config_with_ids.json"
      configured_catalog_path: "integration_tests/configured_catalog.json"
      empty_streams: ["group_issue_boards", "epic_issues"]
      expect_records:
        path: "integration_tests/expected_records_with_ids.txt"
#     test read with OAuth2.0
    - config_path: "secrets/config_oauth.json"
      configured_catalog_path: "integration_tests/configured_catalog.json"
      empty_streams: ["group_issue_boards"]
# We cannot use these tests for testing Incremental, since for Gitlab the State is saved for each Project separately,
# and the Acceptance Tests at this stage do not support this functionality.
# Therefore, we hardcode the cursor_paths for our config.
  incremental:
    - config_path: "secrets/config_with_ids.json"
      configured_catalog_path: "integration_tests/incremental_catalog.json"
      future_state_path: "integration_tests/abnormal_state.json"
      cursor_paths:
        commits: ["25157276", "created_at"]
        issues: ["25157276", "updated_at"]
        merge_requests: ["25157276", "updated_at"]
        pipelines: ["25157276", "updated_at"]
  full_refresh:
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/configured_catalog.json"
